---
version: "3.4"

services:
  db:
    image: "mysql:8"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    env_file:
      - "dev.env"
      - "creds.env"
    volumes:
      - "lcm_mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: "20s"
      retries: 10
volumes:
  lcm_mysql_data:  # yamllint disable-line rule:empty-values
