# Generated by Django 3.2.10 on 2021-12-20 16:27

import django.core.serializers.json
from django.db import migrations, models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0013_default_fallback_value_computedfield"),
        ("nautobot_device_lifecycle_mgmt", "0005_software_reporting"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVELCM",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=16)),
                ("published_date", models.DateField()),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("severity", models.CharField(default="None", max_length=50)),
                ("cvss", models.FloatField(blank=True, null=True)),
                ("cvss_v2", models.FloatField(blank=True, null=True)),
                ("cvss_v3", models.FloatField(blank=True, null=True)),
                ("fix", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True)),
                ("link", models.URLField()),
                (
                    "software",
                    models.ManyToManyField(
                        blank=True,
                        related_name="_nautobot_device_lifecycle_mgmt_cvelcm_software_+",
                        to="nautobot_device_lifecycle_mgmt.SoftwareLCM",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "CVE",
                "ordering": ("severity", "name"),
            },
        ),
    ]
