# Generated by Django 3.1.13 on 2021-11-29 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_device_local_context_schema'),
        ('nautobot_device_lifecycle_mgmt', '0005_reporting_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftwarevalidationresult',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_software_validated', to='dcim.device', unique=True),
        ),
        migrations.AlterField(
            model_name='devicesoftwarevalidationresult',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='nautobot_device_lifecycle_mgmt.softwarelcm'),
        ),
    ]
