# Generated by Django 3.2.10 on 2022-01-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0006_softwareimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareimage',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_images', to='nautobot_device_lifecycle_mgmt.softwarelcm'),
        ),
        migrations.AlterUniqueTogether(
            name='softwareimage',
            unique_together={('image_file_name', 'software')},
        ),
    ]
