# Generated by Django 3.1.13 on 2021-11-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0005_device_local_context_schema'),
        ('nautobot_device_lifecycle_mgmt', '0006_auto_20211129_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesoftwarevalidationresult',
            name='run_type',
            field=models.CharField(default='full-report-run', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitemsoftwarevalidationresult',
            name='run_type',
            field=models.CharField(default='full-report-run', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventoryitemsoftwarevalidationresult',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.inventoryitem', unique=True),
        ),
    ]
