# Generated by Django 3.2.10 on 2022-02-18 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0008_software_image_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="softwarelcm",
            name="download_url",
        ),
        migrations.RemoveField(
            model_name="softwarelcm",
            name="image_file_checksum",
        ),
        migrations.RemoveField(
            model_name="softwarelcm",
            name="image_file_name",
        ),
    ]
