# Generated by Django 3.2.16 on 2023-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0010_softwareimagelcm_hash_algorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="validatedsoftwarelcm",
            name="alias",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
