# Generated by Django 3.2.20 on 2023-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
        ("nautobot_device_lifecycle_mgmt", "0017_set_default_on_text_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractlcm",
            name="devices",
            field=models.ManyToManyField(blank=True, related_name="device_contracts", to="dcim.Device"),
        ),
        migrations.AddField(
            model_name="cvelcm",
            name="affected_softwares",
            field=models.ManyToManyField(
                blank=True, related_name="corresponding_cves", to="nautobot_device_lifecycle_mgmt.SoftwareLCM"
            ),
        ),
        migrations.AlterField(
            model_name="contactlcm",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="contract_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="support_level",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="fix",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="hardwarelcm",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="providerlcm",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="softwarelcm",
            name="alias",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="validatedsoftwarelcm",
            unique_together={("software", "start", "end")},
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitylcm",
            unique_together={("cve", "software", "inventory_item"), ("cve", "software", "device")},
        ),
    ]
