# Generated by Django 3.2.20 on 2023-09-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
        ("nautobot_device_lifecycle_mgmt", "0017_post_nautobot_v2_migrations"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="affected_softwares",
            field=models.ManyToManyField(
                blank=True, related_name="corresponding_cves", to="nautobot_device_lifecycle_mgmt.SoftwareLCM"
            ),
        ),
        migrations.AddField(
            model_name="contractlcm",
            name="devices",
            field=models.ManyToManyField(blank=True, related_name="device_contracts", to="dcim.Device"),
        ),
    ]
