# Generated by Django 3.2.20 on 2023-08-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0017_alter_vulnerabilitylcm_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractlcm",
            name="contract_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="support_level",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="fix",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="hardwarelcm",
            name="comments",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="softwarelcm",
            name="alias",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="validatedsoftwarelcm",
            unique_together={("software", "start", "end")},
        ),
    ]
