# Generated by Django 3.2.21 on 2024-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0020_alter_created_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactlcm",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contactlcm",
            name="name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contactlcm",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="contactlcm",
            name="type",
            field=models.CharField(default="Unassigned", max_length=255),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="contract_type",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="contractlcm",
            name="support_level",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="severity",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AlterField(
            model_name="devicesoftwarevalidationresult",
            name="run_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="run_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="providerlcm",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="providerlcm",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="providerlcm",
            name="phone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="providerlcm",
            name="physical_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="softwareimagelcm",
            name="hashing_algorithm",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="softwareimagelcm",
            name="image_file_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="softwarelcm",
            name="alias",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="softwarelcm",
            name="version",
            field=models.CharField(max_length=255),
        ),
    ]
