# Generated by Django 4.2.14 on 2024-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0021_update_max_char_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwareimagelcm",
            name="inventory_items",
            field=models.ManyToManyField(blank=True, related_name="+", to="dcim.inventoryitem"),
        ),
        migrations.AlterField(
            model_name="softwareimagelcm",
            name="object_tags",
            field=models.ManyToManyField(blank=True, related_name="+", to="extras.tag"),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="device_roles",
            field=models.ManyToManyField(blank=True, related_name="+", to="extras.role"),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="device_types",
            field=models.ManyToManyField(blank=True, related_name="+", to="dcim.devicetype"),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="devices",
            field=models.ManyToManyField(blank=True, related_name="+", to="dcim.device"),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="inventory_items",
            field=models.ManyToManyField(blank=True, related_name="+", to="dcim.inventoryitem"),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="object_tags",
            field=models.ManyToManyField(blank=True, related_name="+", to="extras.tag"),
        ),
    ]
