# Generated by Django 4.2.16 on 2024-11-27 20:45

import nautobot.core.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0114_computedfield_grouping"),
        ("nautobot_device_lifecycle_mgmt", "0022_alter_softwareimagelcm_inventory_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerlcm",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
    ]
