# Generated by Django 4.2.15 on 2024-12-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0022_alter_softwareimagelcm_inventory_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="affected_softwares_tmp",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="devicesoftwarevalidationresult",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="validatedsoftwarelcm",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vulnerabilitylcm",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicesoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="software",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="nautobot_device_lifecycle_mgmt.softwarelcm"
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitylcm",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
    ]
