# Generated by Django 3.2.25 on 2024-11-19 18:33

import django.db.models.deletion
import nautobot.extras.models.statuses
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0098_rename_data_jobresult_result"),
        ("nautobot_device_lifecycle_mgmt", "0022_alter_softwareimagelcm_inventory_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractlcm",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="extras.status",
            ),
        ),
    ]
