# Generated by Django 4.2.15 on 2024-12-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0022_alter_softwareimagelcm_inventory_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="affected_softwares_tmp",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="devicesoftwarevalidationresult",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="validatedsoftwarelcm",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vulnerabilitylcm",
            name="software_tmp",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
