# Generated by Django 4.2.16 on 2024-12-21 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0058_controller_data_migration"),
        ("extras", "0106_populate_default_statuses_and_roles_for_contact_associations"),
        ("nautobot_device_lifecycle_mgmt", "0023_devicehardwarenoticeresult"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="validatedsoftwarelcm",
            options={"ordering": ("preferred", "start"), "verbose_name": "Validated Software"},
        ),
        migrations.AlterUniqueTogether(
            name="validatedsoftwarelcm",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitylcm",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="contactlcm",
            name="migrated_to_core_model",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="extras.contact"
            ),
        ),
        migrations.AddField(
            model_name="contactlcm",
            name="migrated_to_core_model_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="softwareimagelcm",
            name="migrated_to_core_model",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.softwareimagefile"
            ),
        ),
        migrations.AddField(
            model_name="softwareimagelcm",
            name="migrated_to_core_model_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="softwarelcm",
            name="migrated_to_core_model",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="dcim.softwareversion"
            ),
        ),
        migrations.AddField(
            model_name="softwarelcm",
            name="migrated_to_core_model_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="devicesoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="software",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitylcm",
            name="software",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
    ]
