# Generated by Django 3.2.21 on 2024-02-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0023_delete_models_migrated_to_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="last_modified_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
