# Generated by Django 3.2.25 on 2024-08-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0062_module_data_migration"),
        ("nautobot_device_lifecycle_mgmt", "0023_devicehardwarenoticeresult"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="validatedsoftwarelcm",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitylcm",
            unique_together=set(),
        ),
        migrations.RenameField(
            model_name="validatedsoftwarelcm",
            old_name="software",
            new_name="old_software",
        ),
        migrations.RenameField(
            model_name="devicesoftwarevalidationresult",
            old_name="software",
            new_name="old_software",
        ),
        migrations.RenameField(
            model_name="inventoryitemsoftwarevalidationresult",
            old_name="software",
            new_name="old_software",
        ),
        migrations.RenameField(
            model_name="vulnerabilitylcm",
            old_name="software",
            new_name="old_software",
        ),
        migrations.RenameField(
            model_name="cvelcm",
            old_name="affected_softwares",
            new_name="old_affected_softwares",
        ),
        migrations.AddField(
            model_name="cvelcm",
            name="affected_softwares",
            field=models.ManyToManyField(blank=True, related_name="corresponding_cves", to="dcim.softwareversion"),
        ),
        migrations.AddField(
            model_name="devicesoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="dcim.softwareversion",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"
            ),
        ),
        migrations.AddField(
            model_name="validatedsoftwarelcm",
            name="software",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"),
        ),
        migrations.AddField(
            model_name="vulnerabilitylcm",
            name="software",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="validatedsoftwarelcm",
            unique_together={("software", "start", "end")},
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitylcm",
            unique_together={("cve", "software", "inventory_item"), ("cve", "software", "device")},
        ),
    ]
