# Generated by Django 4.2.16 on 2024-12-21 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0058_controller_data_migration"),
        ("nautobot_device_lifecycle_mgmt", "0025_rename_fk_and_m2m_to_models_migrated_to_core"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="validatedsoftwarelcm",
            options={"ordering": ("software", "preferred", "start"), "verbose_name": "Validated Software"},
        ),
        migrations.AddField(
            model_name="cvelcm",
            name="affected_softwares",
            field=models.ManyToManyField(blank=True, related_name="corresponding_cves", to="dcim.softwareversion"),
        ),
        migrations.AddField(
            model_name="devicesoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="dcim.softwareversion",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"
            ),
        ),
        migrations.AddField(
            model_name="validatedsoftwarelcm",
            name="software",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"),
        ),
        migrations.AddField(
            model_name="vulnerabilitylcm",
            name="software",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"
            ),
        ),
        migrations.AlterField(
            model_name="devicesoftwarevalidationresult",
            name="old_software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="old_software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="old_software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilitylcm",
            name="old_software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nautobot_device_lifecycle_mgmt.softwarelcm",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="validatedsoftwarelcm",
            unique_together={("software", "start", "end")},
        ),
        migrations.AlterUniqueTogether(
            name="vulnerabilitylcm",
            unique_together={("cve", "software", "inventory_item"), ("cve", "software", "device")},
        ),
    ]
