# Generated by Django 3.2.25 on 2024-05-01 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0058_controller_data_migration"),
        ("nautobot_device_lifecycle_mgmt", "0026_migrate_soft_references_p2"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="softwareimagelcm",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="device_types",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="inventory_items",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="object_tags",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="software",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="softwarelcm",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="softwarelcm",
            name="device_platform",
        ),
        migrations.RemoveField(
            model_name="softwarelcm",
            name="tags",
        ),
        migrations.DeleteModel(
            name="ContactLCM",
        ),
        migrations.DeleteModel(
            name="SoftwareImageLCM",
        ),
        migrations.DeleteModel(
            name="SoftwareLCM",
        ),
    ]
