# Generated by Django 4.2.16 on 2025-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "nautobot_device_lifecycle_mgmt",
            "0026_add_fk_and_m2m_to_core_software_models",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="last_modified_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
