# Generated by Django 4.2.20 on 2025-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0026_add_fk_and_m2m_to_core_software_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="last_modified_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
