# Generated by Django 4.2.25 on 2025-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0125_jobresult_date_started"),
        ("dcim", "0074_alter_rack_u_height"),
        ("nautobot_device_lifecycle_mgmt", "0027_cvelcm_last_modified_date_alter_cvelcm_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="device_roles",
            field=models.ManyToManyField(
                blank=True, related_name="validatedsoftware_device_roles_tab", to="extras.role"
            ),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="device_types",
            field=models.ManyToManyField(
                blank=True, related_name="validatedsoftware_device_types_tab", to="dcim.devicetype"
            ),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="devices",
            field=models.ManyToManyField(blank=True, related_name="validatedsoftware_devices_tab", to="dcim.device"),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="inventory_items",
            field=models.ManyToManyField(
                blank=True, related_name="validatedsoftware_inventory_items_tab", to="dcim.inventoryitem"
            ),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="object_tags",
            field=models.ManyToManyField(blank=True, related_name="validatedsoftware_object_tags_tab", to="extras.tag"),
        ),
    ]
