# Generated by Django 3.2.25 on 2024-05-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dcim", "0058_controller_data_migration"),
        ("nautobot_device_lifecycle_mgmt", "0027_migrate_soft_references_p5"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="softwareimagelcm",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="device_types",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="inventory_items",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="object_tags",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="software",
        ),
        migrations.RemoveField(
            model_name="softwareimagelcm",
            name="tags",
        ),
        migrations.AlterUniqueTogether(
            name="softwarelcm",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="softwarelcm",
            name="device_platform",
        ),
        migrations.RemoveField(
            model_name="softwarelcm",
            name="tags",
        ),
        migrations.AlterField(
            model_name="cvelcm",
            name="affected_softwares",
            field=models.ManyToManyField(blank=True, related_name="corresponding_cves", to="dcim.SoftwareVersion"),
        ),
        migrations.AlterField(
            model_name="devicesoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="dcim.softwareversion",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"
            ),
        ),
        migrations.AlterField(
            model_name="validatedsoftwarelcm",
            name="software",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"),
        ),
        migrations.AlterField(
            model_name="vulnerabilitylcm",
            name="software",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="dcim.softwareversion"
            ),
        ),
        migrations.DeleteModel(
            name="ContactLCM",
        ),
        migrations.DeleteModel(
            name="SoftwareImageLCM",
        ),
        migrations.DeleteModel(
            name="SoftwareLCM",
        ),
    ]
