# Generated by Django 4.2.20 on 2025-07-08 14:29

import uuid

import django.core.serializers.json
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0027_cvelcm_last_modified_date_alter_cvelcm_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceSoftwareValidationHistoricResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("date", models.DateTimeField()),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("all_tenants", models.BooleanField(default=False)),
                ("all_platforms", models.BooleanField(default=False)),
                ("run_type", models.CharField(max_length=255)),
                ("device_validation_results", models.JSONField(blank=True, default=list)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "Device Software Validation History",
                "ordering": ("date", "run_type"),
                "unique_together": {("date", "run_type")},
            },
            bases=(
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
