# Generated by Django 4.2.26 on 2026-01-16 12:09

import django.db.models.deletion
import nautobot.extras.models.statuses
from django.db import migrations
from nautobot.core.choices import ColorChoices


def create_contract_statuses(apps, schema_editor):
    """Create default statuses for ContractLCM and associate them with the content type."""
    Status = apps.get_model("extras", "Status")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContractLCM = apps.get_model("nautobot_device_lifecycle_mgmt", "ContractLCM")

    contract_ct = ContentType.objects.get_for_model(ContractLCM)

    status_configs = [
        {"name": "Active", "color": ColorChoices.COLOR_GREEN},
        {"name": "Pending Approval", "color": ColorChoices.COLOR_YELLOW},
        {"name": "Renewal Due", "color": ColorChoices.COLOR_DARK_ORANGE},
        {"name": "Terminated", "color": ColorChoices.COLOR_DARK_RED},
        {"name": "Expired", "color": ColorChoices.COLOR_RED},
        {"name": "Month-to-Month", "color": ColorChoices.COLOR_LIME},
    ]

    for config in status_configs:
        status, _ = Status.objects.get_or_create(
            name=config["name"],
            defaults={
                "name": config["name"],
                "color": config["color"],
            },
        )
        # Always ensure the content type is associated with the Contract Statuses
        if contract_ct not in status.content_types.all():
            status.content_types.add(contract_ct)


def remove_contract_statuses(apps, schema_editor):
    """Remove ContractLCM content type from the default statuses."""
    Status = apps.get_model("extras", "Status")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContractLCM = apps.get_model("nautobot_device_lifecycle_mgmt", "ContractLCM")

    contract_ct = ContentType.objects.get_for_model(ContractLCM)

    status_configs = [
        {"name": "Active", "color": ColorChoices.COLOR_GREEN},
        {"name": "Pending Approval", "color": ColorChoices.COLOR_YELLOW},
        {"name": "Renewal Due", "color": ColorChoices.COLOR_DARK_ORANGE},
        {"name": "Terminated", "color": ColorChoices.COLOR_DARK_RED},
        {"name": "Expired", "color": ColorChoices.COLOR_RED},
        {"name": "Month-to-Month", "color": ColorChoices.COLOR_LIME},
    ]

    for config in status_configs:
        try:
            status = Status.objects.get(name=config["name"])
            status.content_types.remove(contract_ct)
        except Status.DoesNotExist:
            pass  # Status may have been deleted by user


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0132_approval_workflow_seed_data"),
        ("nautobot_device_lifecycle_mgmt", "0028_alter_validatedsoftwarelcm_device_roles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractlcm",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
        migrations.RunPython(
            code=create_contract_statuses,
            reverse_code=remove_contract_statuses,
        ),
    ]
