# Generated by Django 4.2.26 on 2026-01-16 12:09

import django.db.models.deletion
import nautobot.extras.models.statuses
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0132_approval_workflow_seed_data"),
        ("nautobot_device_lifecycle_mgmt", "0028_alter_validatedsoftwarelcm_device_roles_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractlcm",
            name="status",
            field=nautobot.extras.models.statuses.StatusField(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.status"
            ),
        ),
    ]
