# Generated by Django 3.2.25 on 2024-05-01 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0028_migrate_soft_references_p4"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="validatedsoftwarelcm",
            name="software_tmp",
        ),
        migrations.RemoveField(
            model_name="devicesoftwarevalidationresult",
            name="software_tmp",
        ),
        migrations.RemoveField(
            model_name="inventoryitemsoftwarevalidationresult",
            name="software_tmp",
        ),
        migrations.RemoveField(
            model_name="cvelcm",
            name="software_tmp",
        ),
        migrations.RemoveField(
            model_name="vulnerabilitylcm",
            name="software_tmp",
        ),
    ]
