# Generated by Django 4.2.16 on 2024-11-27 20:46

from django.db import migrations
import django.db.models.deletion
import nautobot.extras.models.statuses


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0114_computedfield_grouping'),
        ('nautobot_device_lifecycle_mgmt', '0029_devicehardwarenoticeresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractlcm',
            name='status',
            field=nautobot.extras.models.statuses.StatusField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='extras.status'),
        ),
    ]
