# Generated by Django 3.2.25 on 2024-08-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0030_delete_models_migrated_to_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="last_modified_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
