# Generated by Django 3.2.25 on 2024-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_device_lifecycle_mgmt', '0031_devicehardwarenoticeresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvelcm',
            name='last_modified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
