# Generated by Django 5.2.14 on 2026-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_device_lifecycle_mgmt", "0031_validatedsoftwarelcm_device_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvelcm",
            name="cvss_vector",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
