---
name: Deploy to PyPi
on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
      - name: "Set up Python 3.9"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install and configure Poetry"
        uses: "snok/install-poetry@v1.1.1"
        with:
          virtualenvs-create: false
      - name: Publish package if tagged
        uses: JRubics/poetry-publish@v1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
